-- Deprecated: do not apply a standalone Factory schema or demo seed to a
-- business database. The canonical, seed-free command is:
--
--   npm run db:schema
--
-- Existing legacy Factory tables are upgraded non-destructively by
-- scripts/migrations/20260801_factory_schema_v1.sql.
