-- Deprecated compatibility pointer.
--
-- Factory tables now live in the canonical docs/schema.sql and are upgraded
-- by tracked files under scripts/migrations/. Run:
--
--   npm run db:schema
--
-- Keeping a second DDL copy here previously caused INTEGER/NUMERIC, cascade,
-- constraint, and timestamp differences. This file intentionally contains no
-- executable schema so the definitions cannot drift again.
